version: "3.8"

services:
  traefik:
    security_opt:
      - no-new-privileges:true
    image: traefik:v2.6
    container_name: traefik
    restart: always
    networks:
      - traefik-proxy
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro" # Traefik can listen to the Docker events
      - ./traefik.yml:/etc/traefik/traefik.yml:ro # Traefik config
      - ./dynamic.yml:/etc/traefik/dynamic.yml:ro # Middlewares
      - ./acme.json:/acme.json # Certificates will be stored here
    labels:
      - "traefik.enable=true"
      # - "traefik.http.middlewares.traefik-auth.basicauth.users=user:md5_password"
      # - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"

networks:
  traefik-proxy:
    external: true