version: "3.8"

services:
  traefik:
    security_opt:
      - no-new-privileges:true
    image: traefik:v2.6
    container_name: traefik
    restart: always
    networks:
      - traefik-proxy
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./traefik.yml:/traefik.yml:ro
      - ./acme.json:/acme.json

networks:
  traefik-proxy:
    external: true